### ISSUE TITLE
KGE Archive notifications to user subscribers for new file set releases

### ISSUE THREAD

**Issue by RichardBruskiewich** [NCATSTranslator/Knowledge_Graph_Exchange_Registry#34]
Could use  [AWS SNS notification](https://aws.amazon.com/sns/?whats-new-cards.sort-by=item.additionalFields.postDateTime&whats-new-cards.sort-order=desc)

**Comment by jeffhhk** [comment]
Hi, Jeff here from the Unsecret Agent team.  Our team originated this request.

It seems to me a simpler mechanism to notify consumers of new uploads would be to provide an HTTP endpoint called something like GET /v1/get-updates-since?t=<time in seconds since epoch>, which would return a list of uploads completed at time t or later.

Each upload in the list should include:
  - The team originating the artifact
  - The name the originating team gave the artifact (free of versioning information)
  - The semantic version the originating team gave the artifact
  - The time the upload was completed, matching the t= parameter of GET /v1/get-updates-since
  - Any other metadata known about the artifact that is easy to provide

**Comment by jeffhhk** [comment]
I was looking at the defacto HTTP requests this morning.  To find out about new file sets, for now I can probably live with polling this endpoint, once an hour or whatever:

    curl 'https://archive.translator.ncats.io/archive/catalog' -H 'User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Referer: https://archive.translator.ncats.io/home' -H 'Connection: keep-alive' -H 'Cookie: AIOHTTP_SESSION=...' -H 'Sec-Fetch-Dest: empty' -H 'Sec-Fetch-Mode: cors' -H 'Sec-Fetch-Site: same-origin' --silent | jq
        {
          "yeast-sri-reference-kg-tsv": {
            "name": "yeast-sri-reference-kg-tsv",
            "versions": [
              "1.0"
            ]
          }
        }

**Comment by jeffhhk** [comment]
Having looked at the endpoints, and considering no graphs besides my test graph are uploaded, this request feels like premature optimization.  Let's focus first on getting KG producers onboard.  I think the /archive/catalog endpoint will be fine for now.
